version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: semiannually
  groups:
    node-utilities:
      patterns:
      - '*'
- package-ecosystem: bundler
  directory: /
  schedule:
    interval: semiannually
  groups:
    bundler-dependencies:
      patterns:
      - '*'
