---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-case-conflict
    -   id: check-json
        exclude: |
            (?x)^(
                search.json
            )$
    -   id: check-merge-conflict
    -   id: check-toml
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
    -   id: trailing-whitespace

# Checks for spelling errors
-   repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    -   id: codespell

# Format YAML files
-   repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
    -   id: yamlfmt
        args: [--mapping, '4', --sequence, '4', --offset, '0']

# Format TOML files
-   repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.15.0
    hooks:
    -   id: pretty-format-toml
        args: [--autofix, --indent, '4']


-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
    # Run the linter.
    -   id: ruff
        # args: [--statistics]
        args: [--fix, --show-fixes]
    # Run the formatter.
    -   id: ruff-format
        # args: [--diff]
