---
# Website settings
title: Remi Gau
description: Remi's personal website
keywords: Remi,Gau,blog
# baseurl: # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: https://remi-gau.github.io # url should be 'http://<github_username>.github.io/homepage' as before
img_path: /remi-gau.github.io/static/assets/img/blog # url should be '/homepage/static/assets/img/blog' as before

exclude:
-   .pre-commit-config.yaml
-   .ruff_cache
-   .venv
-   cooklang_recipes
-   maint_tools
-   makefile
-   node_modules
-   pyproject.toml
-   vendor


# author -- index page "about me" section
author: # change following line to your information.
    name: RemiGau
    first_name: Remi
    last_name: Gau
    avatar: /static/assets/img/landing/avatar.jpg # upload your avatar at directory and edit it.
    github_username: Remi-Gau
    linkedin_id: remi-gau-bb73141
    facebook_username: remi.gau1
    twitter_username: RemiGau
    mastodon: RemiGau
    email:
    cv: https://github.com/Remi-Gau/CV/raw/master/CV_English.pdf
    # skill icons are on avatar's left and right side.
    # Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
    skill_icon1:
    -   name: fa-biohazard
    -   name: fa-biohazard
    skill_icon2:
    -   name: fa-biohazard
    -   name: fa-biohazard
    desc: I wanted to understand how the brain works, now I tell people how to name files, folders and variables. # Describe yourself.

# comment
disqus: # if you wanna comment feature, go to https://disqus.com/ to get your configuration; if not, comment following two lines.
    name: remi-gau.github.io

# analytics
## google analytics
# ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
# id: UA-116460525-4

## google optimize
# go:
# id:

## growingIO
# gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
# id:

## carousels
index_carousel: on # index page carousel switch
blog_carousel: on # blog page carousel switch

# scss
sass:
    style: compressed

# Build settings
encoding: UTF-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
    input: GFM
    syntax_highlighter: rouge

plugins:
-   jekyll-redirect-from

whitelist:
-   jekyll-redirect-from

relative_links:
    enabled: true
    collections: true

collections:
    recipes:
        output: true
        permalink: /:collection/:name/

defaults:
-   scope:
        path: '' # an empty string here means all files in the project
    values:
        blog_carousel: on
-   scope:
        path: _recipes/en
    values:
        layout: recipe
        permalink: /recipe/en/:slug
        locale: en
-   scope:
        path: _recipes/fr
    values:
        layout: recipe
        permalink: /recipe/fr/:slug
        locale: fr
